driver:
  name: docker

provisioner:
  name: chef_zero

always_update_cookbooks: true
product_name: chef
product_version: 14

verifier:
 name: inspec
  
platforms:
 - name: ubuntu-18.04
 
suites:
 - name: default
   run_list:
     - recipe[pache::default]
   verifier:
    inspec_tests:
     - test/integration/default
   
  
