name 'apache-exapmle'
maintainer 'The Authors'
maintainer_email 'you@example.com'
license 'All Rights Reserved'
description 'Installs/Configures apache-exapmle'
long_description 'Installs/Configures apache-exapmle'
version '0.1.0'
chef_version '>= 14.0'
